/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package publicsectorservice;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class DOWNLOADFORMS extends javax.swing.JFrame {

    /**
     * Creates new form DOWNLOADFORMS
     */
    public DOWNLOADFORMS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("MARJ HELPLINE CENTRE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 380, 50));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("DOWNLOAD VARIOUS KINDS OF FORMS HERE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 440, -1));

        jLabel3.setText("SELECT THE FORM WHICH YOU WANT TO DOWNLOAD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 460, 60));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "        Aadhar card form", "Driving Licence form", "Medical Certifcate", "PAN Card Application Form", "Marriage Registration", "Surrender of Permit and clearance", "Encumbrance certificate", "Authorization of tourist permit", "Passport Application Form", "Trade Certficate", " " }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 239, 200, 30));

        jButton1.setText("Download");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 120, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\NETBEANS PROJECT\\publicsectorservice\\039fee8fdd06a3ac415798d0757e2b51.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 770, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        switch(jComboBox1.getSelectedIndex())
        {
            case 0: try{
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Admin\\Desktop\\NETBEANS PROJECT\\publicsectorservice\\aadhar new and correction form.pdf");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            break;
            case 1: try{
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Admin\\Desktop\\NETBEANS PROJECT\\publicsectorservice\\DRIVING LICENCE FORM.pdf");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            break;
            case 2: try{
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Admin\\Desktop\\NETBEANS PROJECT\\publicsectorservice\\MEDICAL CERTFICATE.pdf");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            break;
            case 3: try{
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Admin\\Desktop\\NETBEANS PROJECT\\publicsectorservice\\PAN FORM.pdf");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            break;
            case 4: try{
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Admin\\Desktop\\NETBEANS PROJECT\\publicsectorservice\\Marriage registration.pdf");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            break;
            case 5: try{
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Admin\\Desktop\\NETBEANS PROJECT\\publicsectorservice\\Surrender of permit and clearance.pdf");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            break;
            case 6: try{
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Admin\\Desktop\\NETBEANS PROJECT\\publicsectorservice\\Encumbrance certificate.pdf");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            break;
            case 7: try{
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Admin\\Desktop\\NETBEANS PROJECT\\publicsectorservice\\Authorization for tourist permit.pdf");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            break;
            case 8: try{
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Admin\\Desktop\\NETBEANS PROJECT\\publicsectorservice\\PASSPORT APPLICATION FORM.pdf");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            break;
            case 9: try{
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Admin\\Desktop\\NETBEANS PROJECT\\publicsectorservice\\Trade certificate.pdf");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DOWNLOADFORMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DOWNLOADFORMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DOWNLOADFORMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DOWNLOADFORMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DOWNLOADFORMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
